### ISSUE TITLE
Input textfield - Improve styling with no required attribute?

### ISSUE THREAD

**Issue by adam-knights** [mildrenben/surface#12]
Thank you for your great work.

If I omit the the required attribute then the style of the textfield is permanently valid. The floating effect also then doesn't work. Would it be possible for you to add styling so that textfields can work without the required attribute?

I've seen other libraries use the class="validate" for when a user does want validation styling.

If I change line 23 of form.scss from   `&:focus, &:valid {` to `&:focus {` then I no longer have to include the required attribute, although the placeholder label does still float back down so I guess more would be required.

**Comment by mildrenben** [comment]
Hey @adam-knights ! I spent a lot of time looking into this when I first made Surface. It actually cannot be done with pure CSS alone whilst maintaining the same styling as the inputs with required. It would need to be done with JS. Surface was kind of just an experiment to see how much could be done with pure CSS and no JS, so I chose not to include any JS solutions.

(Just to clarify, just because it was a semi-experiment doesn't mean you cannot/shouldn't use it in production, I've used it plenty).

If you wanted to add that in to your personal project, simply make a class with all the styling for the required input fields and call it validate like you said. Then in JS target all the validate classes and give them more styling based on whether they're onfocus or not.

Thanks :)
